# Generated by Django 5.2.10 on 2026-02-03 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='📁', help_text='Emoji per icona categoria', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Ordine visualizzazione (crescente)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria App',
                'verbose_name_plural': 'Categorie App',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome App')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('icon', models.CharField(default='📱', help_text='Emoji per icona', max_length=10)),
                ('color_from', models.CharField(default='#667eea', help_text='Colore iniziale gradiente (es: #667eea)', max_length=7)),
                ('color_to', models.CharField(default='#764ba2', help_text='Colore finale gradiente (es: #764ba2)', max_length=7)),
                ('app_type', models.CharField(choices=[('internal_url', 'Link Interno'), ('external_url', 'Link Esterno'), ('html_page', 'Pagina HTML'), ('iframe', 'Iframe Embedded')], default='internal_url', max_length=20, verbose_name='Tipo App')),
                ('url', models.CharField(blank=True, help_text='URL o path relativo (es: /apps/dashboard/ o https://example.com)', max_length=500)),
                ('html_content', models.TextField(blank=True, help_text='Contenuto HTML completo (per app_type=html_page)')),
                ('order', models.IntegerField(default=0, help_text='Ordine visualizzazione')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
                ('is_public', models.BooleanField(default=False, help_text='Visibile senza login')),
                ('requires_sso', models.BooleanField(default=True, help_text='Usa autenticazione MyApp (SSO)')),
                ('allowed_roles', models.CharField(default='admin,editor,viewer', help_text='Ruoli separati da virgola (admin,editor,viewer)', max_length=200)),
                ('click_count', models.IntegerField(default=0, verbose_name='Numero accessi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps', to='apphub.appcategory')),
            ],
            options={
                'verbose_name': 'Applicazione',
                'verbose_name_plural': 'Applicazioni',
                'ordering': ['order', 'name'],
            },
        ),
    ]
